create-pages:
    pages: true
      script:
          - mkdir public
              - cp -r ./* public/
                  - rm -rf public/public
                    artifacts:
                        paths:
                              - public